### ISSUE TITLE
svgToPdf is not working when no starting point for path

### ISSUE THREAD

**Issue by zezo93** [alafr/SVG-to-PDFKit#107]
Hi, 
I tried to transform an svg to pdf, and here is my code:

```
var fs = require('fs'),
    PDFDocument = require('pdfkit'),
    SVGtoPDF = require('svg-to-pdfkit');

var doc = new PDFDocument(),
    stream = fs.createWriteStream('file.pdf'),
    svg = `<svg viewBox="0 0 6 6" xmlns="http://www.w3.org/2000/svg">
  <path d="M1,5 a2,2 0,0,0 2,-3 a3,3 0 0 1 2,3" stroke="black" fill="none"
        stroke-linejoin="round" />
		
    <path class="highcharts-graph" d="m4 92h200l200-4.1181" fill="none" stroke="#ff9800" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" data-z-index="1"/>
	<path class="highcharts-graph" d="m404 16.296" fill="none" stroke="#2C313F" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" data-z-index="1"/>
	

</svg>`;

SVGtoPDF(doc, svg, 0, 0);

stream.on('finish', function() {
  console.log(fs.readFileSync('file.pdf'))
});

doc.pipe(stream);
doc.end();
```
And i got this error: 
```
TypeError: Cannot read property '0' of null
    at SvgElemPath.SvgElemBasicShape.drawInDocument (C:\Users\azaareer\Desktop\svgpdf\node_modules\svg-to-pdfkit\source.js:1791:51)
    at SvgElemSvg.SvgElemHasChildren.drawChildren (C:\Users\azaareer\Desktop\svgpdf\node_modules\svg-to-pdfkit\source.js:1386:27)
    at SvgElemSvg.SvgElemContainer.drawContent (C:\Users\azaareer\Desktop\svgpdf\node_modules\svg-to-pdfkit\source.js:1403:14)
    at SvgElemSvg.drawInDocument (C:\Users\azaareer\Desktop\svgpdf\node_modules\svg-to-pdfkit\source.js:1518:14)
    at SVGtoPDF (C:\Users\azaareer\Desktop\svgpdf\node_modules\svg-to-pdfkit\source.js:2473:14)
    at Object.<anonymous> (C:\Users\azaareer\Desktop\svgpdf\svg-pdf.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

```
Note that Svg is working fine, and i find out the 3rd path starting point is null  ==> [here](https://github.com/alafr/SVG-to-PDFKit/blob/035594be0af8db7c41d5fd9ad80d93e518c86768/source.js#L1813)

**Comment by alafr** [comment]
This bug has been fixed by PR #99, I will soon publish a new release
